export const buttonPressAudio = new Audio('./assets/button-press.wav')
export const kitchenTimer = new Audio('./assets/kichen-timer.mp3')
export const bgAudio = new Audio('./assets/bg-audio.mp3')
export const bgFloresta = new Audio('/assets/Floresta.wav')
export const bgChuva = new Audio('/assets/Chuva.wav')
export const bgCafeteria = new Audio('/assets/Cafeteria.wav')
export const bgLareira = new Audio('/assets/Lareira.wav')